[general]
mode = "default"
sharpness_override = -1.0

[resolution_override]
native = 0.35
quality = 0.666667
balanced = 0.26
performance = 0.5
ultra_performance = 0.27
ultra_quality = 0.27

[compatibility]
fake_nvidia_gpu = true
fake_nvapi_results = true
amd_unreal_engine_dlss_workaround = true
macos_crossover_support = true

[logging]
disable_console = false

[debug]
enable_debug_view = true
enable_debug_tear_lines = false
