class TekkenOverlayCommon::BusinessLayer::DefaultFontChanger:
  Enabled: false
  FontSize: 20
class TekkenOverlayCommon::BusinessLayer::FPSUnlocker:
  IsEnabled: true
  FPS: 144
class TekkenOverlayCommon::BusinessLayer::PerformanceStages:
  ShouldCreateSimplifiedStage: false
  ShouldReplaceAllMaterialsWithDefaultMaterial: false
  ShouldDisableAllLights: false
  ShouldDisableClothPhysics: false
  ShouldDisableEffects: false
  ShouldDisableCameraShakes: false
class TekkenOverlayCommon::BusinessLayer::AddConsoleMod:
  Enabled: false
class Tekken8Overlay::BusinessLayer::Interpolation:
  Enabled: true
class Tekken8Overlay::BusinessLayer::NetworkLag:
  Enabled: false
  InputLag: 0
class Tekken8Overlay::BusinessLayer::DisplaySettings:
  WantedGlobalIlluminationQuality: 3
  WantedReflectionQuality: 3
  WantedGlobalIlluminationMethod: 0
  WantedReflectionMethod: 2
  WantedAAMethod: 2
  WantedLightColor:
    R: 1
    G: 1
    B: 1
    A: 1
  LastAppliedConfig: ""
  ShouldDisablePostProcessingVolumes: false
  ShouldDisableBakedInLighting: false
  ShouldDisableUpscaling: false
  ShouldDisableCharacterLights: false
  ShouldApplyCustomCharacterLightingColor: false
  ShouldDisableOtherLights: false
  OLEDFix: false
OverlayTotalUsageTime: 248