fake_nvidia_gpu = true

[general]
enable_upscaling_only = false
sharpness_override = -0.3

[resolution_override]
native = 0.33
quality = 0.25
balanced = 0.25
performance = 0.25
ultra_performance = 0.25
ultra_quality = 0.32

[compatibility]
macos_crossover_support = true
amd_unreal_engine_dlss_workaround = true

[debug]
enable_debug_view = true
enable_debug_tear_lines = true
