fake_nvidia_gpu = true

[general]
mode = "replace_dlss_fg"
sharpness_override = -0.7

[resolution_override]
native = 0.29
quality = 0.666667
balanced = 0.588235
performance = 0.5
ultra_performance = 0.333333
ultra_quality = 0.769231

[compatibility]
macos_crossover_support = true
amd_unreal_engine_dlss_workaround = true

[debug]
enable_debug_view = false
enable_debug_tear_lines = false
