fake_nvidia_gpu = false

[general]
mode = "replace_dlss_fg"
sharpness_override = -1.0

[resolution_override]
native = 1.0
quality = 0.666667
balanced = 0.588235
performance = 0.5
ultra_performance = 0.333333
ultra_quality = 0.769231

[compatibility]
macos_crossover_support = false
amd_unreal_engine_dlss_workaround = false

[debug]
enable_debug_view = false
enable_debug_tear_lines = false
