fake_nvidia_gpu = true

[general]
mode = "replace_dlss_fg"
sharpness_override = -1.0

[resolution_override]
native = 0.29
quality = 0.27
balanced = 0.31
performance = 0.27
ultra_performance = 0.26
ultra_quality = 0.29

[compatibility]
macos_crossover_support = false
amd_unreal_engine_dlss_workaround = false

[debug]
enable_debug_view = false
enable_debug_tear_lines = false
