fake_nvidia_gpu = false

[general]
mode = "use_game_upscaling"
sharpness_override = -0.3

[resolution_override]
native = 0.26
quality = 0.26
balanced = 0.26
performance = 0.26
ultra_performance = 0.26
ultra_quality = 0.27

[compatibility]
macos_crossover_support = true
amd_unreal_engine_dlss_workaround = true

[debug]
enable_debug_view = true
enable_debug_tear_lines = false
